#ifndef EXT_CONSTS_H
#define EXT_CONSTS_H


#include "bbs/consts.h"
#include "ext_config.h"
#include "ext_permissions.h"
#include "ext_mode.h"

/* php代码中使用的常量 */
/* REGISTER_STRING_CONSTANT(char *name, char *value, int flags);  */
/* REGISTER_STRINGL_CONSTANT(char *name, char *value, int size, int flags);  */
/* REGISTER_LONG_CONSTANT(char *name, int value, int flags);  */
/* flags: CONST_CS 大小写敏感， CONST_PERSISTENT 保持不变 */

#define REGISTER_ALL_PHP_CONSTANT				\
    REGISTER_STRING_CONSTANT("BBSHOME", BBSHOME, CONST_CS | CONST_PERSISTENT);	\
    REGISTER_STRING_CONSTANT("BBSNAME", BBSNAME, CONST_CS | CONST_PERSISTENT);	\
    REGISTER_STRING_CONSTANT("BBSID", BBSID, CONST_CS | CONST_PERSISTENT);		\
    REGISTER_STRING_CONSTANT("BBSHOST", BBSHOST, CONST_CS | CONST_PERSISTENT);	\
    REGISTER_STRING_CONSTANT("BBSIP", BBSIP, CONST_CS | CONST_PERSISTENT);		\
    REGISTER_STRING_CONSTANT("DEFAULTBOARD", DEFAULTBOARD, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_STRING_CONSTANT("DEFAULTFAVBOARD", DEFAULTFAVBOARD, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_STRING_CONSTANT("DEFAULTRECOMMENDBOARD", DEFAULTRECOMMENDBOARD, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_PERM_CONSTANTS						\
	REGISTER_MODE_CONSTANTS						\
	REGISTER_LONG_CONSTANT("FILE_READ", FILE_READ, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_OWND", FILE_OWND, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_VISIT", FILE_VISIT, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_MARKED", FILE_MARKED, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_DIGEST", FILE_DIGEST, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_FORWARDED", FILE_FORWARDED, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("MAIL_REPLY", MAIL_REPLY, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_NOREPLY", FILE_NOREPLY, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_DELETED", FILE_DELETED, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_SELECTED", FILE_SELECTED, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_ATTACHED", FILE_ATTACHED, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_RECOMMENDED", FILE_RECOMMENDED, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("FILE_MAIL", FILE_MAIL, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("FILE_OUTPOST", FILE_OUTPOST, CONST_CS | CONST_PERSISTENT);	\
    REGISTER_LONG_CONSTANT("FILE_REPLYNOTIFY", FILE_REPLYNOTIFY, CONST_CS | CONST_PERSISTENT);	\ 
	REGISTER_LONG_CONSTANT("VOTE_FLAG", VOTE_FLAG, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("NOZAP_FLAG", NOZAP_FLAG, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("OUT_FLAG", OUT_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("ANONY_FLAG", ANONY_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("NOREPLY_FLAG", NOREPLY_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("READONLY_FLAG", READONLY_FLAG, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("JUNK_FLAG", JUNK_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("NOPLIMIT_FLAG", JUNK_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("BRD_READONLY", BRD_READONLY, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("BRD_RESTRICT", BRD_RESTRICT, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("BRD_NOPOSTVOTE", BRD_NOPOSTVOTE, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("BRD_ATTACH", BRD_ATTACH, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("BRD_GROUP", BRD_GROUP, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("BRD_HALFOPEN", BRD_HALFOPEN, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("BRD_INTERN", BRD_INTERN, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("BRD_MAXII_FLAG", BRD_MAXII_FLAG, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("MAX_BOARD_POST", MAX_BOARD_POST, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("MAX_BOARD_POST_II", MAX_BOARD_POST_II, CONST_CS | CONST_PERSISTENT);		\
	REGISTER_LONG_CONSTANT("MAX_USERICON", MAX_USERICON, CONST_CS | CONST_PERSISTENT);		\
    	REGISTER_LONG_CONSTANT("BRC_MAXNUM", BRC_MAXNUM, CONST_CS | CONST_PERSISTENT);		\
    






#endif // EXT_CONSTS_H

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: noet sw=4 ts=4 fdm=marker
 * vim<600: noet sw=4 ts=4
 */

