#ifndef EXT_PERMISSIONS_H
#define EXT_PERMISSIONS_H

#include "bbs/permissions.h"

/*
  convert from permissions.h:
  grep "#define PERM_" permissions.h  >> tmpfile
  perl -p -e "s/^#define (PERM_\w+).*$/REGISTER_LONG_CONSTANT\(\"\1\", \1, CONST_CS | CONST_PERSISTENT); \\\/" tmpfile
*/

#define REGISTER_PERM_CONSTANTS			\
	REGISTER_LONG_CONSTANT("PERM_BASIC", PERM_BASIC, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_CHAT", PERM_CHAT, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_PAGE", PERM_PAGE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_POST", PERM_POST, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_LOGINOK", PERM_LOGINOK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_DENYPOST", PERM_DENYPOST, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_CLOAK", PERM_CLOAK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SEECLOAK", PERM_SEECLOAK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_XEMPT", PERM_XEMPT, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_WELCOME", PERM_WELCOME, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_BOARDS", PERM_BOARDS, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ACCOUNTS", PERM_ACCOUNTS, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_CHATCLOAK", PERM_CHATCLOAK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_OVOTE", PERM_OVOTE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SYSOP", PERM_SYSOP, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_POSTMASK", PERM_POSTMASK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ANNOUNCE", PERM_ANNOUNCE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_OBOARDS", PERM_OBOARDS, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ACBOARD", PERM_ACBOARD, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_NOZAP", PERM_NOZAP, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_FORCEPAGE", PERM_FORCEPAGE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_EXT_IDLE", PERM_EXT_IDLE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_MESSAGE", PERM_MESSAGE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SENDMAIL", PERM_SENDMAIL, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SEEIP", PERM_SEEIP, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_INTERNAL", PERM_INTERNAL, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_PERSONAL", PERM_PERSONAL, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_JUDGE", PERM_JUDGE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ACHATROOM", PERM_ACHATROOM, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SUICIDE", PERM_SUICIDE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_DEFAULT", PERM_DEFAULT, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ADMINMENU", PERM_ADMINMENU, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_MULTILOG", PERM_MULTILOG, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_ESYSFILE", PERM_ESYSFILE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_LOGINCLOAK", PERM_LOGINCLOAK, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SEEULEVELS", PERM_SEEULEVELS, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_BLEVELS", PERM_BLEVELS, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_MARKPOST", PERM_MARKPOST, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_UCLEAN", PERM_UCLEAN, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_NOTIMEOUT", PERM_NOTIMEOUT, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_READMAIL", PERM_READMAIL, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_VOTE", PERM_VOTE, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_LARGEMAIL", PERM_LARGEMAIL, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_SETADDR", PERM_SETADDR, CONST_CS | CONST_PERSISTENT);	\
	REGISTER_LONG_CONSTANT("PERM_FORWARD", PERM_FORWARD, CONST_CS | CONST_PERSISTENT);	\
	

#endif // EXT_PERMISSIONS_H

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: noet sw=4 ts=4 fdm=marker
 * vim<600: noet sw=4 ts=4
 */

