#ifndef EXT_MODE_H
#define EXT_MODE_H

#include "bbs/permissions.h"

/*
  convert from modes.h:
  grep -P -o "#define \w+[ \t]" modes.h  > tmpfile
  perl -p -e "s/^#define (\w+)[ \t]/REGISTER_LONG_CONSTANT\(\"STAT_\1\", \1, CONST_CS | CONST_PERSISTENT); \\\/" tmpfile
  
*/

#define REGISTER_MODE_CONSTANTS											\
	REGISTER_LONG_CONSTANT("STAT_IDLE", IDLE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_TALK", TALK, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_NEW", NEW, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_READNEW", READNEW, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_POSTING", POSTING, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_LAUSERS", LAUSERS, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_LUSERS", LUSERS, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_SMAIL", SMAIL, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_RMAIL", RMAIL, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_MMENU", MMENU, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_TMENU", TMENU, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_XMENU", XMENU, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_READING", READING, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_PAGE", PAGE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_ADMIN", ADMIN, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_READBRD", READBRD, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_SELECT", SELECT, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_LOGIN", LOGIN, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_MONITOR", MONITOR, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_CHAT1", CHAT1, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_CHAT2", CHAT2, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_CHAT3", CHAT3, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_CHAT4", CHAT4, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_ZAP", ZAP, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_EDITUFILE", EDITUFILE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_EDITSFILE", EDITSFILE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_QUERY", QUERY, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_CNTBRDS", CNTBRDS, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_VOTING", VOTING, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_VISIT", VISIT, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_BBSNET", BBSNET, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_FRIEND", FRIEND, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_YANKING", YANKING, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_GMENU", GMENU, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_DICT", DICT, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_LOCKSCREEN", LOCKSCREEN, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_NOTEPAD", NOTEPAD, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_MSG", MSG, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_USERDEF", USERDEF, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_EDIT", EDIT, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_OFFLINE", OFFLINE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_EDITANN", EDITANN, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_LOOKMSGS", LOOKMSGS, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_WFRIEND", WFRIEND, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_SYSINFO", SYSINFO, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_WNOTEPAD", WNOTEPAD, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_WINMINE", WINMINE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_FIVE", FIVE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_PAGE_FIVE", PAGE_FIVE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_ALL_GAMES", ALL_GAMES, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_DATAMANAGE", DATAMANAGE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_DIGEST", DIGEST, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_DIGESTRACE", DIGESTRACE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_MOBILE", MOBILE, CONST_CS | CONST_PERSISTENT); \
	REGISTER_LONG_CONSTANT("STAT_WWW", WWW, CONST_CS | CONST_PERSISTENT); \
	
	

#endif // EXT_MODE_H

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: noet sw=4 ts=4 fdm=marker
 * vim<600: noet sw=4 ts=4
 */
